//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportationService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenses
    {
        public int id { get; set; }
        public int driver_id { get; set; }
        public int vehicle_type_id { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Vehicle_types Vehicle_types { get; set; }
    }
}
