//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportationService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transports
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public Nullable<int> distance { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<decimal> income { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
